# Generated by Django 4.2.7 on 2023-11-08 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_alter_book_genre_reviews_message_club'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
